#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xfwm4
Version  : 4.13.1
Release  : 24
URL      : http://archive.xfce.org/src/xfce/xfwm4/4.13/xfwm4-4.13.1.tar.bz2
Source0  : http://archive.xfce.org/src/xfce/xfwm4/4.13/xfwm4-4.13.1.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: xfwm4-bin = %{version}-%{release}
Requires: xfwm4-data = %{version}-%{release}
Requires: xfwm4-license = %{version}-%{release}
Requires: xfwm4-locales = %{version}-%{release}
BuildRequires : intltool
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libwnck-1.0)
BuildRequires : pkgconfig(libwnck-3.0)
BuildRequires : pkgconfig(libxfce4kbd-private-3)
BuildRequires : pkgconfig(libxfce4ui-1)
BuildRequires : pkgconfig(libxfce4ui-2)
BuildRequires : pkgconfig(libxfce4util-1.0)
BuildRequires : pkgconfig(libxfconf-0)
BuildRequires : pkgconfig(presentproto)
BuildRequires : pkgconfig(sm)
BuildRequires : pkgconfig(xcomposite)
BuildRequires : pkgconfig(xdamage)
BuildRequires : pkgconfig(xfixes)
BuildRequires : pkgconfig(xinerama)
BuildRequires : pkgconfig(xpresent)
BuildRequires : pkgconfig(xrender)
Patch1: 0001-Set-default-visual-styling.patch

%description
-= xfwm4 =-
This is the window manager for Xfce (http://www.xfce.org).
Xfwm is compliant with the following specifications from the freedesktop.org
(http://www.freedesktop.org/) standards:

%package bin
Summary: bin components for the xfwm4 package.
Group: Binaries
Requires: xfwm4-data = %{version}-%{release}
Requires: xfwm4-license = %{version}-%{release}

%description bin
bin components for the xfwm4 package.


%package data
Summary: data components for the xfwm4 package.
Group: Data

%description data
data components for the xfwm4 package.


%package license
Summary: license components for the xfwm4 package.
Group: Default

%description license
license components for the xfwm4 package.


%package locales
Summary: locales components for the xfwm4 package.
Group: Default

%description locales
locales components for the xfwm4 package.


%prep
%setup -q -n xfwm4-4.13.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542224843
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1542224843
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xfwm4
cp COPYING %{buildroot}/usr/share/package-licenses/xfwm4/COPYING
%make_install
%find_lang xfwm4

%files
%defattr(-,root,root,-)
/usr/lib64/xfce4/xfwm4/helper-dialog

%files bin
%defattr(-,root,root,-)
/usr/bin/xfwm4
/usr/bin/xfwm4-settings
/usr/bin/xfwm4-tweaks-settings
/usr/bin/xfwm4-workspace-settings

%files data
%defattr(-,root,root,-)
/usr/share/applications/xfce-wm-settings.desktop
/usr/share/applications/xfce-wmtweaks-settings.desktop
/usr/share/applications/xfce-workspaces-settings.desktop
/usr/share/icons/hicolor/22x22/actions/xfce-wm-close.png
/usr/share/icons/hicolor/22x22/actions/xfce-wm-maximize.png
/usr/share/icons/hicolor/22x22/actions/xfce-wm-menu.png
/usr/share/icons/hicolor/22x22/actions/xfce-wm-minimize.png
/usr/share/icons/hicolor/22x22/actions/xfce-wm-shade.png
/usr/share/icons/hicolor/22x22/actions/xfce-wm-stick.png
/usr/share/icons/hicolor/22x22/actions/xfce-wm-unmaximize.png
/usr/share/icons/hicolor/22x22/actions/xfce-wm-unshade.png
/usr/share/icons/hicolor/22x22/actions/xfce-wm-unstick.png
/usr/share/icons/hicolor/48x48/apps/wmtweaks.png
/usr/share/icons/hicolor/48x48/apps/xfce4-workspaces.png
/usr/share/icons/hicolor/48x48/apps/xfwm4-default.png
/usr/share/icons/hicolor/48x48/apps/xfwm4.png
/usr/share/icons/hicolor/scalable/actions/xfce-wm-close.svg
/usr/share/icons/hicolor/scalable/actions/xfce-wm-maximize.svg
/usr/share/icons/hicolor/scalable/actions/xfce-wm-menu.svg
/usr/share/icons/hicolor/scalable/actions/xfce-wm-minimize.svg
/usr/share/icons/hicolor/scalable/actions/xfce-wm-shade.svg
/usr/share/icons/hicolor/scalable/actions/xfce-wm-stick.svg
/usr/share/icons/hicolor/scalable/actions/xfce-wm-unmaximize.svg
/usr/share/icons/hicolor/scalable/actions/xfce-wm-unshade.svg
/usr/share/icons/hicolor/scalable/actions/xfce-wm-unstick.svg
/usr/share/icons/hicolor/scalable/apps/wmtweaks.svg
/usr/share/icons/hicolor/scalable/apps/xfce4-workspaces.svg
/usr/share/icons/hicolor/scalable/apps/xfwm4-default.svg
/usr/share/icons/hicolor/scalable/apps/xfwm4.svg
/usr/share/themes/Daloa/xfwm4/README
/usr/share/themes/Daloa/xfwm4/bottom-active.png
/usr/share/themes/Daloa/xfwm4/bottom-active.xpm
/usr/share/themes/Daloa/xfwm4/bottom-inactive.png
/usr/share/themes/Daloa/xfwm4/bottom-inactive.xpm
/usr/share/themes/Daloa/xfwm4/bottom-left-active.png
/usr/share/themes/Daloa/xfwm4/bottom-left-active.xpm
/usr/share/themes/Daloa/xfwm4/bottom-left-inactive.png
/usr/share/themes/Daloa/xfwm4/bottom-left-inactive.xpm
/usr/share/themes/Daloa/xfwm4/bottom-right-active.png
/usr/share/themes/Daloa/xfwm4/bottom-right-active.xpm
/usr/share/themes/Daloa/xfwm4/bottom-right-inactive.png
/usr/share/themes/Daloa/xfwm4/bottom-right-inactive.xpm
/usr/share/themes/Daloa/xfwm4/close-active.png
/usr/share/themes/Daloa/xfwm4/close-active.xpm
/usr/share/themes/Daloa/xfwm4/close-inactive.png
/usr/share/themes/Daloa/xfwm4/close-inactive.xpm
/usr/share/themes/Daloa/xfwm4/close-prelight.png
/usr/share/themes/Daloa/xfwm4/close-prelight.xpm
/usr/share/themes/Daloa/xfwm4/close-pressed.png
/usr/share/themes/Daloa/xfwm4/close-pressed.xpm
/usr/share/themes/Daloa/xfwm4/hide-active.png
/usr/share/themes/Daloa/xfwm4/hide-active.xpm
/usr/share/themes/Daloa/xfwm4/hide-inactive.png
/usr/share/themes/Daloa/xfwm4/hide-inactive.xpm
/usr/share/themes/Daloa/xfwm4/hide-prelight.png
/usr/share/themes/Daloa/xfwm4/hide-prelight.xpm
/usr/share/themes/Daloa/xfwm4/hide-pressed.png
/usr/share/themes/Daloa/xfwm4/hide-pressed.xpm
/usr/share/themes/Daloa/xfwm4/left-active.png
/usr/share/themes/Daloa/xfwm4/left-active.xpm
/usr/share/themes/Daloa/xfwm4/left-inactive.png
/usr/share/themes/Daloa/xfwm4/left-inactive.xpm
/usr/share/themes/Daloa/xfwm4/maximize-active.png
/usr/share/themes/Daloa/xfwm4/maximize-active.xpm
/usr/share/themes/Daloa/xfwm4/maximize-inactive.png
/usr/share/themes/Daloa/xfwm4/maximize-inactive.xpm
/usr/share/themes/Daloa/xfwm4/maximize-prelight.png
/usr/share/themes/Daloa/xfwm4/maximize-prelight.xpm
/usr/share/themes/Daloa/xfwm4/maximize-pressed.png
/usr/share/themes/Daloa/xfwm4/maximize-pressed.xpm
/usr/share/themes/Daloa/xfwm4/maximize-toggled-active.png
/usr/share/themes/Daloa/xfwm4/maximize-toggled-active.xpm
/usr/share/themes/Daloa/xfwm4/maximize-toggled-inactive.png
/usr/share/themes/Daloa/xfwm4/maximize-toggled-inactive.xpm
/usr/share/themes/Daloa/xfwm4/maximize-toggled-prelight.png
/usr/share/themes/Daloa/xfwm4/maximize-toggled-prelight.xpm
/usr/share/themes/Daloa/xfwm4/maximize-toggled-pressed.png
/usr/share/themes/Daloa/xfwm4/maximize-toggled-pressed.xpm
/usr/share/themes/Daloa/xfwm4/menu-active.png
/usr/share/themes/Daloa/xfwm4/menu-active.xpm
/usr/share/themes/Daloa/xfwm4/menu-inactive.png
/usr/share/themes/Daloa/xfwm4/menu-inactive.xpm
/usr/share/themes/Daloa/xfwm4/menu-prelight.png
/usr/share/themes/Daloa/xfwm4/menu-prelight.xpm
/usr/share/themes/Daloa/xfwm4/menu-pressed.png
/usr/share/themes/Daloa/xfwm4/menu-pressed.xpm
/usr/share/themes/Daloa/xfwm4/right-active.png
/usr/share/themes/Daloa/xfwm4/right-active.xpm
/usr/share/themes/Daloa/xfwm4/right-inactive.png
/usr/share/themes/Daloa/xfwm4/right-inactive.xpm
/usr/share/themes/Daloa/xfwm4/shade-active.png
/usr/share/themes/Daloa/xfwm4/shade-active.xpm
/usr/share/themes/Daloa/xfwm4/shade-inactive.png
/usr/share/themes/Daloa/xfwm4/shade-inactive.xpm
/usr/share/themes/Daloa/xfwm4/shade-prelight.png
/usr/share/themes/Daloa/xfwm4/shade-prelight.xpm
/usr/share/themes/Daloa/xfwm4/shade-pressed.png
/usr/share/themes/Daloa/xfwm4/shade-pressed.xpm
/usr/share/themes/Daloa/xfwm4/shade-toggled-active.png
/usr/share/themes/Daloa/xfwm4/shade-toggled-active.xpm
/usr/share/themes/Daloa/xfwm4/shade-toggled-inactive.png
/usr/share/themes/Daloa/xfwm4/shade-toggled-inactive.xpm
/usr/share/themes/Daloa/xfwm4/shade-toggled-prelight.png
/usr/share/themes/Daloa/xfwm4/shade-toggled-prelight.xpm
/usr/share/themes/Daloa/xfwm4/shade-toggled-pressed.png
/usr/share/themes/Daloa/xfwm4/shade-toggled-pressed.xpm
/usr/share/themes/Daloa/xfwm4/stick-active.png
/usr/share/themes/Daloa/xfwm4/stick-active.xpm
/usr/share/themes/Daloa/xfwm4/stick-inactive.png
/usr/share/themes/Daloa/xfwm4/stick-inactive.xpm
/usr/share/themes/Daloa/xfwm4/stick-prelight.png
/usr/share/themes/Daloa/xfwm4/stick-prelight.xpm
/usr/share/themes/Daloa/xfwm4/stick-pressed.png
/usr/share/themes/Daloa/xfwm4/stick-pressed.xpm
/usr/share/themes/Daloa/xfwm4/stick-toggled-active.png
/usr/share/themes/Daloa/xfwm4/stick-toggled-active.xpm
/usr/share/themes/Daloa/xfwm4/stick-toggled-inactive.png
/usr/share/themes/Daloa/xfwm4/stick-toggled-inactive.xpm
/usr/share/themes/Daloa/xfwm4/stick-toggled-prelight.png
/usr/share/themes/Daloa/xfwm4/stick-toggled-prelight.xpm
/usr/share/themes/Daloa/xfwm4/stick-toggled-pressed.png
/usr/share/themes/Daloa/xfwm4/stick-toggled-pressed.xpm
/usr/share/themes/Daloa/xfwm4/themerc
/usr/share/themes/Daloa/xfwm4/title-1-active.png
/usr/share/themes/Daloa/xfwm4/title-1-active.xpm
/usr/share/themes/Daloa/xfwm4/title-1-inactive.png
/usr/share/themes/Daloa/xfwm4/title-1-inactive.xpm
/usr/share/themes/Daloa/xfwm4/title-2-active.png
/usr/share/themes/Daloa/xfwm4/title-2-active.xpm
/usr/share/themes/Daloa/xfwm4/title-2-inactive.png
/usr/share/themes/Daloa/xfwm4/title-2-inactive.xpm
/usr/share/themes/Daloa/xfwm4/title-3-active.png
/usr/share/themes/Daloa/xfwm4/title-3-active.xpm
/usr/share/themes/Daloa/xfwm4/title-3-inactive.png
/usr/share/themes/Daloa/xfwm4/title-3-inactive.xpm
/usr/share/themes/Daloa/xfwm4/title-4-active.png
/usr/share/themes/Daloa/xfwm4/title-4-active.xpm
/usr/share/themes/Daloa/xfwm4/title-4-inactive.png
/usr/share/themes/Daloa/xfwm4/title-4-inactive.xpm
/usr/share/themes/Daloa/xfwm4/title-5-active.png
/usr/share/themes/Daloa/xfwm4/title-5-active.xpm
/usr/share/themes/Daloa/xfwm4/title-5-inactive.png
/usr/share/themes/Daloa/xfwm4/title-5-inactive.xpm
/usr/share/themes/Daloa/xfwm4/top-left-active.png
/usr/share/themes/Daloa/xfwm4/top-left-active.xpm
/usr/share/themes/Daloa/xfwm4/top-left-inactive.png
/usr/share/themes/Daloa/xfwm4/top-left-inactive.xpm
/usr/share/themes/Daloa/xfwm4/top-right-active.png
/usr/share/themes/Daloa/xfwm4/top-right-active.xpm
/usr/share/themes/Daloa/xfwm4/top-right-inactive.png
/usr/share/themes/Daloa/xfwm4/top-right-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/README
/usr/share/themes/Default-hdpi/xfwm4/bottom-active.png
/usr/share/themes/Default-hdpi/xfwm4/bottom-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/bottom-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/bottom-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/bottom-left-active.png
/usr/share/themes/Default-hdpi/xfwm4/bottom-left-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/bottom-left-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/bottom-left-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/bottom-right-active.png
/usr/share/themes/Default-hdpi/xfwm4/bottom-right-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/bottom-right-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/bottom-right-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/close-active.png
/usr/share/themes/Default-hdpi/xfwm4/close-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/close-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/close-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/close-prelight.png
/usr/share/themes/Default-hdpi/xfwm4/close-prelight.xpm
/usr/share/themes/Default-hdpi/xfwm4/close-pressed.png
/usr/share/themes/Default-hdpi/xfwm4/close-pressed.xpm
/usr/share/themes/Default-hdpi/xfwm4/hide-active.png
/usr/share/themes/Default-hdpi/xfwm4/hide-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/hide-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/hide-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/hide-prelight.png
/usr/share/themes/Default-hdpi/xfwm4/hide-prelight.xpm
/usr/share/themes/Default-hdpi/xfwm4/hide-pressed.png
/usr/share/themes/Default-hdpi/xfwm4/hide-pressed.xpm
/usr/share/themes/Default-hdpi/xfwm4/left-active.png
/usr/share/themes/Default-hdpi/xfwm4/left-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/left-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/left-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/maximize-active.png
/usr/share/themes/Default-hdpi/xfwm4/maximize-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/maximize-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/maximize-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/maximize-prelight.png
/usr/share/themes/Default-hdpi/xfwm4/maximize-prelight.xpm
/usr/share/themes/Default-hdpi/xfwm4/maximize-pressed.png
/usr/share/themes/Default-hdpi/xfwm4/maximize-pressed.xpm
/usr/share/themes/Default-hdpi/xfwm4/maximize-toggled-active.png
/usr/share/themes/Default-hdpi/xfwm4/maximize-toggled-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/maximize-toggled-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/maximize-toggled-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/maximize-toggled-prelight.png
/usr/share/themes/Default-hdpi/xfwm4/maximize-toggled-prelight.xpm
/usr/share/themes/Default-hdpi/xfwm4/maximize-toggled-pressed.png
/usr/share/themes/Default-hdpi/xfwm4/maximize-toggled-pressed.xpm
/usr/share/themes/Default-hdpi/xfwm4/menu-active.png
/usr/share/themes/Default-hdpi/xfwm4/menu-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/menu-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/menu-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/menu-prelight.png
/usr/share/themes/Default-hdpi/xfwm4/menu-prelight.xpm
/usr/share/themes/Default-hdpi/xfwm4/menu-pressed.png
/usr/share/themes/Default-hdpi/xfwm4/menu-pressed.xpm
/usr/share/themes/Default-hdpi/xfwm4/right-active.png
/usr/share/themes/Default-hdpi/xfwm4/right-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/right-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/right-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/shade-active.png
/usr/share/themes/Default-hdpi/xfwm4/shade-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/shade-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/shade-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/shade-prelight.png
/usr/share/themes/Default-hdpi/xfwm4/shade-prelight.xpm
/usr/share/themes/Default-hdpi/xfwm4/shade-pressed.png
/usr/share/themes/Default-hdpi/xfwm4/shade-pressed.xpm
/usr/share/themes/Default-hdpi/xfwm4/shade-toggled-active.png
/usr/share/themes/Default-hdpi/xfwm4/shade-toggled-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/shade-toggled-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/shade-toggled-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/shade-toggled-prelight.png
/usr/share/themes/Default-hdpi/xfwm4/shade-toggled-prelight.xpm
/usr/share/themes/Default-hdpi/xfwm4/shade-toggled-pressed.png
/usr/share/themes/Default-hdpi/xfwm4/shade-toggled-pressed.xpm
/usr/share/themes/Default-hdpi/xfwm4/stick-active.png
/usr/share/themes/Default-hdpi/xfwm4/stick-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/stick-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/stick-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/stick-prelight.png
/usr/share/themes/Default-hdpi/xfwm4/stick-prelight.xpm
/usr/share/themes/Default-hdpi/xfwm4/stick-pressed.png
/usr/share/themes/Default-hdpi/xfwm4/stick-pressed.xpm
/usr/share/themes/Default-hdpi/xfwm4/stick-toggled-active.png
/usr/share/themes/Default-hdpi/xfwm4/stick-toggled-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/stick-toggled-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/stick-toggled-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/stick-toggled-prelight.png
/usr/share/themes/Default-hdpi/xfwm4/stick-toggled-prelight.xpm
/usr/share/themes/Default-hdpi/xfwm4/stick-toggled-pressed.png
/usr/share/themes/Default-hdpi/xfwm4/stick-toggled-pressed.xpm
/usr/share/themes/Default-hdpi/xfwm4/themerc
/usr/share/themes/Default-hdpi/xfwm4/title-1-active.png
/usr/share/themes/Default-hdpi/xfwm4/title-1-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/title-1-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/title-1-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/title-2-active.png
/usr/share/themes/Default-hdpi/xfwm4/title-2-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/title-2-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/title-2-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/title-3-active.png
/usr/share/themes/Default-hdpi/xfwm4/title-3-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/title-3-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/title-3-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/title-4-active.png
/usr/share/themes/Default-hdpi/xfwm4/title-4-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/title-4-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/title-4-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/title-5-active.png
/usr/share/themes/Default-hdpi/xfwm4/title-5-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/title-5-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/title-5-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/top-left-active.png
/usr/share/themes/Default-hdpi/xfwm4/top-left-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/top-left-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/top-left-inactive.xpm
/usr/share/themes/Default-hdpi/xfwm4/top-right-active.png
/usr/share/themes/Default-hdpi/xfwm4/top-right-active.xpm
/usr/share/themes/Default-hdpi/xfwm4/top-right-inactive.png
/usr/share/themes/Default-hdpi/xfwm4/top-right-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/README
/usr/share/themes/Default-xhdpi/xfwm4/bottom-active.png
/usr/share/themes/Default-xhdpi/xfwm4/bottom-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/bottom-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/bottom-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/bottom-left-active.png
/usr/share/themes/Default-xhdpi/xfwm4/bottom-left-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/bottom-left-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/bottom-left-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/bottom-right-active.png
/usr/share/themes/Default-xhdpi/xfwm4/bottom-right-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/bottom-right-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/bottom-right-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/close-active.png
/usr/share/themes/Default-xhdpi/xfwm4/close-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/close-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/close-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/close-prelight.png
/usr/share/themes/Default-xhdpi/xfwm4/close-prelight.xpm
/usr/share/themes/Default-xhdpi/xfwm4/close-pressed.png
/usr/share/themes/Default-xhdpi/xfwm4/close-pressed.xpm
/usr/share/themes/Default-xhdpi/xfwm4/hide-active.png
/usr/share/themes/Default-xhdpi/xfwm4/hide-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/hide-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/hide-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/hide-prelight.png
/usr/share/themes/Default-xhdpi/xfwm4/hide-prelight.xpm
/usr/share/themes/Default-xhdpi/xfwm4/hide-pressed.png
/usr/share/themes/Default-xhdpi/xfwm4/hide-pressed.xpm
/usr/share/themes/Default-xhdpi/xfwm4/left-active.png
/usr/share/themes/Default-xhdpi/xfwm4/left-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/left-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/left-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/maximize-active.png
/usr/share/themes/Default-xhdpi/xfwm4/maximize-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/maximize-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/maximize-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/maximize-prelight.png
/usr/share/themes/Default-xhdpi/xfwm4/maximize-prelight.xpm
/usr/share/themes/Default-xhdpi/xfwm4/maximize-pressed.png
/usr/share/themes/Default-xhdpi/xfwm4/maximize-pressed.xpm
/usr/share/themes/Default-xhdpi/xfwm4/maximize-toggled-active.png
/usr/share/themes/Default-xhdpi/xfwm4/maximize-toggled-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/maximize-toggled-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/maximize-toggled-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/maximize-toggled-prelight.png
/usr/share/themes/Default-xhdpi/xfwm4/maximize-toggled-prelight.xpm
/usr/share/themes/Default-xhdpi/xfwm4/maximize-toggled-pressed.png
/usr/share/themes/Default-xhdpi/xfwm4/maximize-toggled-pressed.xpm
/usr/share/themes/Default-xhdpi/xfwm4/menu-active.png
/usr/share/themes/Default-xhdpi/xfwm4/menu-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/menu-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/menu-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/menu-prelight.png
/usr/share/themes/Default-xhdpi/xfwm4/menu-prelight.xpm
/usr/share/themes/Default-xhdpi/xfwm4/menu-pressed.png
/usr/share/themes/Default-xhdpi/xfwm4/menu-pressed.xpm
/usr/share/themes/Default-xhdpi/xfwm4/right-active.png
/usr/share/themes/Default-xhdpi/xfwm4/right-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/right-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/right-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/shade-active.png
/usr/share/themes/Default-xhdpi/xfwm4/shade-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/shade-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/shade-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/shade-prelight.png
/usr/share/themes/Default-xhdpi/xfwm4/shade-prelight.xpm
/usr/share/themes/Default-xhdpi/xfwm4/shade-pressed.png
/usr/share/themes/Default-xhdpi/xfwm4/shade-pressed.xpm
/usr/share/themes/Default-xhdpi/xfwm4/shade-toggled-active.png
/usr/share/themes/Default-xhdpi/xfwm4/shade-toggled-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/shade-toggled-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/shade-toggled-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/shade-toggled-prelight.png
/usr/share/themes/Default-xhdpi/xfwm4/shade-toggled-prelight.xpm
/usr/share/themes/Default-xhdpi/xfwm4/shade-toggled-pressed.png
/usr/share/themes/Default-xhdpi/xfwm4/shade-toggled-pressed.xpm
/usr/share/themes/Default-xhdpi/xfwm4/stick-active.png
/usr/share/themes/Default-xhdpi/xfwm4/stick-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/stick-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/stick-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/stick-prelight.png
/usr/share/themes/Default-xhdpi/xfwm4/stick-prelight.xpm
/usr/share/themes/Default-xhdpi/xfwm4/stick-pressed.png
/usr/share/themes/Default-xhdpi/xfwm4/stick-pressed.xpm
/usr/share/themes/Default-xhdpi/xfwm4/stick-toggled-active.png
/usr/share/themes/Default-xhdpi/xfwm4/stick-toggled-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/stick-toggled-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/stick-toggled-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/stick-toggled-prelight.png
/usr/share/themes/Default-xhdpi/xfwm4/stick-toggled-prelight.xpm
/usr/share/themes/Default-xhdpi/xfwm4/stick-toggled-pressed.png
/usr/share/themes/Default-xhdpi/xfwm4/stick-toggled-pressed.xpm
/usr/share/themes/Default-xhdpi/xfwm4/themerc
/usr/share/themes/Default-xhdpi/xfwm4/title-1-active.png
/usr/share/themes/Default-xhdpi/xfwm4/title-1-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/title-1-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/title-1-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/title-2-active.png
/usr/share/themes/Default-xhdpi/xfwm4/title-2-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/title-2-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/title-2-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/title-3-active.png
/usr/share/themes/Default-xhdpi/xfwm4/title-3-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/title-3-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/title-3-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/title-4-active.png
/usr/share/themes/Default-xhdpi/xfwm4/title-4-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/title-4-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/title-4-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/title-5-active.png
/usr/share/themes/Default-xhdpi/xfwm4/title-5-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/title-5-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/title-5-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/top-left-active.png
/usr/share/themes/Default-xhdpi/xfwm4/top-left-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/top-left-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/top-left-inactive.xpm
/usr/share/themes/Default-xhdpi/xfwm4/top-right-active.png
/usr/share/themes/Default-xhdpi/xfwm4/top-right-active.xpm
/usr/share/themes/Default-xhdpi/xfwm4/top-right-inactive.png
/usr/share/themes/Default-xhdpi/xfwm4/top-right-inactive.xpm
/usr/share/themes/Default/xfwm4/README
/usr/share/themes/Default/xfwm4/bottom-active.png
/usr/share/themes/Default/xfwm4/bottom-active.xpm
/usr/share/themes/Default/xfwm4/bottom-inactive.png
/usr/share/themes/Default/xfwm4/bottom-inactive.xpm
/usr/share/themes/Default/xfwm4/bottom-left-active.png
/usr/share/themes/Default/xfwm4/bottom-left-active.xpm
/usr/share/themes/Default/xfwm4/bottom-left-inactive.png
/usr/share/themes/Default/xfwm4/bottom-left-inactive.xpm
/usr/share/themes/Default/xfwm4/bottom-right-active.png
/usr/share/themes/Default/xfwm4/bottom-right-active.xpm
/usr/share/themes/Default/xfwm4/bottom-right-inactive.png
/usr/share/themes/Default/xfwm4/bottom-right-inactive.xpm
/usr/share/themes/Default/xfwm4/close-active.png
/usr/share/themes/Default/xfwm4/close-active.xpm
/usr/share/themes/Default/xfwm4/close-inactive.png
/usr/share/themes/Default/xfwm4/close-inactive.xpm
/usr/share/themes/Default/xfwm4/close-prelight.png
/usr/share/themes/Default/xfwm4/close-prelight.xpm
/usr/share/themes/Default/xfwm4/close-pressed.png
/usr/share/themes/Default/xfwm4/close-pressed.xpm
/usr/share/themes/Default/xfwm4/hide-active.png
/usr/share/themes/Default/xfwm4/hide-active.xpm
/usr/share/themes/Default/xfwm4/hide-inactive.png
/usr/share/themes/Default/xfwm4/hide-inactive.xpm
/usr/share/themes/Default/xfwm4/hide-prelight.png
/usr/share/themes/Default/xfwm4/hide-prelight.xpm
/usr/share/themes/Default/xfwm4/hide-pressed.png
/usr/share/themes/Default/xfwm4/hide-pressed.xpm
/usr/share/themes/Default/xfwm4/left-active.png
/usr/share/themes/Default/xfwm4/left-active.xpm
/usr/share/themes/Default/xfwm4/left-inactive.png
/usr/share/themes/Default/xfwm4/left-inactive.xpm
/usr/share/themes/Default/xfwm4/maximize-active.png
/usr/share/themes/Default/xfwm4/maximize-active.xpm
/usr/share/themes/Default/xfwm4/maximize-inactive.png
/usr/share/themes/Default/xfwm4/maximize-inactive.xpm
/usr/share/themes/Default/xfwm4/maximize-prelight.png
/usr/share/themes/Default/xfwm4/maximize-prelight.xpm
/usr/share/themes/Default/xfwm4/maximize-pressed.png
/usr/share/themes/Default/xfwm4/maximize-pressed.xpm
/usr/share/themes/Default/xfwm4/maximize-toggled-active.png
/usr/share/themes/Default/xfwm4/maximize-toggled-active.xpm
/usr/share/themes/Default/xfwm4/maximize-toggled-inactive.png
/usr/share/themes/Default/xfwm4/maximize-toggled-inactive.xpm
/usr/share/themes/Default/xfwm4/maximize-toggled-prelight.png
/usr/share/themes/Default/xfwm4/maximize-toggled-prelight.xpm
/usr/share/themes/Default/xfwm4/maximize-toggled-pressed.png
/usr/share/themes/Default/xfwm4/maximize-toggled-pressed.xpm
/usr/share/themes/Default/xfwm4/menu-active.png
/usr/share/themes/Default/xfwm4/menu-active.xpm
/usr/share/themes/Default/xfwm4/menu-inactive.png
/usr/share/themes/Default/xfwm4/menu-inactive.xpm
/usr/share/themes/Default/xfwm4/menu-prelight.png
/usr/share/themes/Default/xfwm4/menu-prelight.xpm
/usr/share/themes/Default/xfwm4/menu-pressed.png
/usr/share/themes/Default/xfwm4/menu-pressed.xpm
/usr/share/themes/Default/xfwm4/right-active.png
/usr/share/themes/Default/xfwm4/right-active.xpm
/usr/share/themes/Default/xfwm4/right-inactive.png
/usr/share/themes/Default/xfwm4/right-inactive.xpm
/usr/share/themes/Default/xfwm4/shade-active.png
/usr/share/themes/Default/xfwm4/shade-active.xpm
/usr/share/themes/Default/xfwm4/shade-inactive.png
/usr/share/themes/Default/xfwm4/shade-inactive.xpm
/usr/share/themes/Default/xfwm4/shade-prelight.png
/usr/share/themes/Default/xfwm4/shade-prelight.xpm
/usr/share/themes/Default/xfwm4/shade-pressed.png
/usr/share/themes/Default/xfwm4/shade-pressed.xpm
/usr/share/themes/Default/xfwm4/shade-toggled-active.png
/usr/share/themes/Default/xfwm4/shade-toggled-active.xpm
/usr/share/themes/Default/xfwm4/shade-toggled-inactive.png
/usr/share/themes/Default/xfwm4/shade-toggled-inactive.xpm
/usr/share/themes/Default/xfwm4/shade-toggled-prelight.png
/usr/share/themes/Default/xfwm4/shade-toggled-prelight.xpm
/usr/share/themes/Default/xfwm4/shade-toggled-pressed.png
/usr/share/themes/Default/xfwm4/shade-toggled-pressed.xpm
/usr/share/themes/Default/xfwm4/stick-active.png
/usr/share/themes/Default/xfwm4/stick-active.xpm
/usr/share/themes/Default/xfwm4/stick-inactive.png
/usr/share/themes/Default/xfwm4/stick-inactive.xpm
/usr/share/themes/Default/xfwm4/stick-prelight.png
/usr/share/themes/Default/xfwm4/stick-prelight.xpm
/usr/share/themes/Default/xfwm4/stick-pressed.png
/usr/share/themes/Default/xfwm4/stick-pressed.xpm
/usr/share/themes/Default/xfwm4/stick-toggled-active.png
/usr/share/themes/Default/xfwm4/stick-toggled-active.xpm
/usr/share/themes/Default/xfwm4/stick-toggled-inactive.png
/usr/share/themes/Default/xfwm4/stick-toggled-inactive.xpm
/usr/share/themes/Default/xfwm4/stick-toggled-prelight.png
/usr/share/themes/Default/xfwm4/stick-toggled-prelight.xpm
/usr/share/themes/Default/xfwm4/stick-toggled-pressed.png
/usr/share/themes/Default/xfwm4/stick-toggled-pressed.xpm
/usr/share/themes/Default/xfwm4/themerc
/usr/share/themes/Default/xfwm4/title-1-active.png
/usr/share/themes/Default/xfwm4/title-1-active.xpm
/usr/share/themes/Default/xfwm4/title-1-inactive.png
/usr/share/themes/Default/xfwm4/title-1-inactive.xpm
/usr/share/themes/Default/xfwm4/title-2-active.png
/usr/share/themes/Default/xfwm4/title-2-active.xpm
/usr/share/themes/Default/xfwm4/title-2-inactive.png
/usr/share/themes/Default/xfwm4/title-2-inactive.xpm
/usr/share/themes/Default/xfwm4/title-3-active.png
/usr/share/themes/Default/xfwm4/title-3-active.xpm
/usr/share/themes/Default/xfwm4/title-3-inactive.png
/usr/share/themes/Default/xfwm4/title-3-inactive.xpm
/usr/share/themes/Default/xfwm4/title-4-active.png
/usr/share/themes/Default/xfwm4/title-4-active.xpm
/usr/share/themes/Default/xfwm4/title-4-inactive.png
/usr/share/themes/Default/xfwm4/title-4-inactive.xpm
/usr/share/themes/Default/xfwm4/title-5-active.png
/usr/share/themes/Default/xfwm4/title-5-active.xpm
/usr/share/themes/Default/xfwm4/title-5-inactive.png
/usr/share/themes/Default/xfwm4/title-5-inactive.xpm
/usr/share/themes/Default/xfwm4/top-left-active.png
/usr/share/themes/Default/xfwm4/top-left-active.xpm
/usr/share/themes/Default/xfwm4/top-left-inactive.png
/usr/share/themes/Default/xfwm4/top-left-inactive.xpm
/usr/share/themes/Default/xfwm4/top-right-active.png
/usr/share/themes/Default/xfwm4/top-right-active.xpm
/usr/share/themes/Default/xfwm4/top-right-inactive.png
/usr/share/themes/Default/xfwm4/top-right-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/README
/usr/share/themes/Kokodi/xfwm4/bottom-active.png
/usr/share/themes/Kokodi/xfwm4/bottom-active.xpm
/usr/share/themes/Kokodi/xfwm4/bottom-inactive.png
/usr/share/themes/Kokodi/xfwm4/bottom-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/bottom-left-active.png
/usr/share/themes/Kokodi/xfwm4/bottom-left-active.xpm
/usr/share/themes/Kokodi/xfwm4/bottom-left-inactive.png
/usr/share/themes/Kokodi/xfwm4/bottom-left-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/bottom-right-active.png
/usr/share/themes/Kokodi/xfwm4/bottom-right-active.xpm
/usr/share/themes/Kokodi/xfwm4/bottom-right-inactive.png
/usr/share/themes/Kokodi/xfwm4/bottom-right-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/close-active.png
/usr/share/themes/Kokodi/xfwm4/close-active.xpm
/usr/share/themes/Kokodi/xfwm4/close-inactive.png
/usr/share/themes/Kokodi/xfwm4/close-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/close-prelight.png
/usr/share/themes/Kokodi/xfwm4/close-prelight.xpm
/usr/share/themes/Kokodi/xfwm4/close-pressed.png
/usr/share/themes/Kokodi/xfwm4/close-pressed.xpm
/usr/share/themes/Kokodi/xfwm4/hide-active.png
/usr/share/themes/Kokodi/xfwm4/hide-active.xpm
/usr/share/themes/Kokodi/xfwm4/hide-inactive.png
/usr/share/themes/Kokodi/xfwm4/hide-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/hide-prelight.png
/usr/share/themes/Kokodi/xfwm4/hide-prelight.xpm
/usr/share/themes/Kokodi/xfwm4/hide-pressed.png
/usr/share/themes/Kokodi/xfwm4/hide-pressed.xpm
/usr/share/themes/Kokodi/xfwm4/left-active.png
/usr/share/themes/Kokodi/xfwm4/left-active.xpm
/usr/share/themes/Kokodi/xfwm4/left-inactive.png
/usr/share/themes/Kokodi/xfwm4/left-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/maximize-active.png
/usr/share/themes/Kokodi/xfwm4/maximize-active.xpm
/usr/share/themes/Kokodi/xfwm4/maximize-inactive.png
/usr/share/themes/Kokodi/xfwm4/maximize-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/maximize-prelight.png
/usr/share/themes/Kokodi/xfwm4/maximize-prelight.xpm
/usr/share/themes/Kokodi/xfwm4/maximize-pressed.png
/usr/share/themes/Kokodi/xfwm4/maximize-pressed.xpm
/usr/share/themes/Kokodi/xfwm4/maximize-toggled-active.png
/usr/share/themes/Kokodi/xfwm4/maximize-toggled-active.xpm
/usr/share/themes/Kokodi/xfwm4/maximize-toggled-inactive.png
/usr/share/themes/Kokodi/xfwm4/maximize-toggled-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/maximize-toggled-prelight.png
/usr/share/themes/Kokodi/xfwm4/maximize-toggled-prelight.xpm
/usr/share/themes/Kokodi/xfwm4/maximize-toggled-pressed.png
/usr/share/themes/Kokodi/xfwm4/maximize-toggled-pressed.xpm
/usr/share/themes/Kokodi/xfwm4/menu-active.png
/usr/share/themes/Kokodi/xfwm4/menu-active.xpm
/usr/share/themes/Kokodi/xfwm4/menu-inactive.png
/usr/share/themes/Kokodi/xfwm4/menu-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/menu-prelight.png
/usr/share/themes/Kokodi/xfwm4/menu-prelight.xpm
/usr/share/themes/Kokodi/xfwm4/menu-pressed.png
/usr/share/themes/Kokodi/xfwm4/menu-pressed.xpm
/usr/share/themes/Kokodi/xfwm4/right-active.png
/usr/share/themes/Kokodi/xfwm4/right-active.xpm
/usr/share/themes/Kokodi/xfwm4/right-inactive.png
/usr/share/themes/Kokodi/xfwm4/right-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/shade-active.png
/usr/share/themes/Kokodi/xfwm4/shade-active.xpm
/usr/share/themes/Kokodi/xfwm4/shade-inactive.png
/usr/share/themes/Kokodi/xfwm4/shade-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/shade-prelight.png
/usr/share/themes/Kokodi/xfwm4/shade-prelight.xpm
/usr/share/themes/Kokodi/xfwm4/shade-pressed.png
/usr/share/themes/Kokodi/xfwm4/shade-pressed.xpm
/usr/share/themes/Kokodi/xfwm4/shade-toggled-active.png
/usr/share/themes/Kokodi/xfwm4/shade-toggled-active.xpm
/usr/share/themes/Kokodi/xfwm4/shade-toggled-inactive.png
/usr/share/themes/Kokodi/xfwm4/shade-toggled-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/shade-toggled-prelight.png
/usr/share/themes/Kokodi/xfwm4/shade-toggled-prelight.xpm
/usr/share/themes/Kokodi/xfwm4/shade-toggled-pressed.png
/usr/share/themes/Kokodi/xfwm4/shade-toggled-pressed.xpm
/usr/share/themes/Kokodi/xfwm4/stick-active.png
/usr/share/themes/Kokodi/xfwm4/stick-active.xpm
/usr/share/themes/Kokodi/xfwm4/stick-inactive.png
/usr/share/themes/Kokodi/xfwm4/stick-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/stick-prelight.png
/usr/share/themes/Kokodi/xfwm4/stick-prelight.xpm
/usr/share/themes/Kokodi/xfwm4/stick-pressed.png
/usr/share/themes/Kokodi/xfwm4/stick-pressed.xpm
/usr/share/themes/Kokodi/xfwm4/stick-toggled-active.png
/usr/share/themes/Kokodi/xfwm4/stick-toggled-active.xpm
/usr/share/themes/Kokodi/xfwm4/stick-toggled-inactive.png
/usr/share/themes/Kokodi/xfwm4/stick-toggled-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/stick-toggled-prelight.png
/usr/share/themes/Kokodi/xfwm4/stick-toggled-prelight.xpm
/usr/share/themes/Kokodi/xfwm4/stick-toggled-pressed.png
/usr/share/themes/Kokodi/xfwm4/stick-toggled-pressed.xpm
/usr/share/themes/Kokodi/xfwm4/themerc
/usr/share/themes/Kokodi/xfwm4/title-1-active.png
/usr/share/themes/Kokodi/xfwm4/title-1-active.xpm
/usr/share/themes/Kokodi/xfwm4/title-1-inactive.png
/usr/share/themes/Kokodi/xfwm4/title-1-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/title-2-active.png
/usr/share/themes/Kokodi/xfwm4/title-2-active.xpm
/usr/share/themes/Kokodi/xfwm4/title-2-inactive.png
/usr/share/themes/Kokodi/xfwm4/title-2-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/title-3-active.png
/usr/share/themes/Kokodi/xfwm4/title-3-active.xpm
/usr/share/themes/Kokodi/xfwm4/title-3-inactive.png
/usr/share/themes/Kokodi/xfwm4/title-3-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/title-4-active.png
/usr/share/themes/Kokodi/xfwm4/title-4-active.xpm
/usr/share/themes/Kokodi/xfwm4/title-4-inactive.png
/usr/share/themes/Kokodi/xfwm4/title-4-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/title-5-active.png
/usr/share/themes/Kokodi/xfwm4/title-5-active.xpm
/usr/share/themes/Kokodi/xfwm4/title-5-inactive.png
/usr/share/themes/Kokodi/xfwm4/title-5-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/top-left-active.png
/usr/share/themes/Kokodi/xfwm4/top-left-active.xpm
/usr/share/themes/Kokodi/xfwm4/top-left-inactive.png
/usr/share/themes/Kokodi/xfwm4/top-left-inactive.xpm
/usr/share/themes/Kokodi/xfwm4/top-right-active.png
/usr/share/themes/Kokodi/xfwm4/top-right-active.xpm
/usr/share/themes/Kokodi/xfwm4/top-right-inactive.png
/usr/share/themes/Kokodi/xfwm4/top-right-inactive.xpm
/usr/share/themes/Moheli/xfwm4/README
/usr/share/themes/Moheli/xfwm4/bottom-active.png
/usr/share/themes/Moheli/xfwm4/bottom-active.xpm
/usr/share/themes/Moheli/xfwm4/bottom-inactive.png
/usr/share/themes/Moheli/xfwm4/bottom-inactive.xpm
/usr/share/themes/Moheli/xfwm4/bottom-left-active.png
/usr/share/themes/Moheli/xfwm4/bottom-left-active.xpm
/usr/share/themes/Moheli/xfwm4/bottom-left-inactive.png
/usr/share/themes/Moheli/xfwm4/bottom-left-inactive.xpm
/usr/share/themes/Moheli/xfwm4/bottom-right-active.png
/usr/share/themes/Moheli/xfwm4/bottom-right-active.xpm
/usr/share/themes/Moheli/xfwm4/bottom-right-inactive.png
/usr/share/themes/Moheli/xfwm4/bottom-right-inactive.xpm
/usr/share/themes/Moheli/xfwm4/close-active.png
/usr/share/themes/Moheli/xfwm4/close-active.xpm
/usr/share/themes/Moheli/xfwm4/close-inactive.png
/usr/share/themes/Moheli/xfwm4/close-inactive.xpm
/usr/share/themes/Moheli/xfwm4/close-pressed.png
/usr/share/themes/Moheli/xfwm4/close-pressed.xpm
/usr/share/themes/Moheli/xfwm4/hide-active.png
/usr/share/themes/Moheli/xfwm4/hide-active.xpm
/usr/share/themes/Moheli/xfwm4/hide-inactive.png
/usr/share/themes/Moheli/xfwm4/hide-inactive.xpm
/usr/share/themes/Moheli/xfwm4/hide-pressed.png
/usr/share/themes/Moheli/xfwm4/hide-pressed.xpm
/usr/share/themes/Moheli/xfwm4/left-active.png
/usr/share/themes/Moheli/xfwm4/left-active.xpm
/usr/share/themes/Moheli/xfwm4/left-inactive.png
/usr/share/themes/Moheli/xfwm4/left-inactive.xpm
/usr/share/themes/Moheli/xfwm4/maximize-active.png
/usr/share/themes/Moheli/xfwm4/maximize-active.xpm
/usr/share/themes/Moheli/xfwm4/maximize-inactive.png
/usr/share/themes/Moheli/xfwm4/maximize-inactive.xpm
/usr/share/themes/Moheli/xfwm4/maximize-pressed.png
/usr/share/themes/Moheli/xfwm4/maximize-pressed.xpm
/usr/share/themes/Moheli/xfwm4/maximize-toggled-active.png
/usr/share/themes/Moheli/xfwm4/maximize-toggled-active.xpm
/usr/share/themes/Moheli/xfwm4/maximize-toggled-inactive.png
/usr/share/themes/Moheli/xfwm4/maximize-toggled-inactive.xpm
/usr/share/themes/Moheli/xfwm4/maximize-toggled-pressed.png
/usr/share/themes/Moheli/xfwm4/maximize-toggled-pressed.xpm
/usr/share/themes/Moheli/xfwm4/menu-active.png
/usr/share/themes/Moheli/xfwm4/menu-active.xpm
/usr/share/themes/Moheli/xfwm4/menu-inactive.png
/usr/share/themes/Moheli/xfwm4/menu-inactive.xpm
/usr/share/themes/Moheli/xfwm4/menu-pressed.png
/usr/share/themes/Moheli/xfwm4/menu-pressed.xpm
/usr/share/themes/Moheli/xfwm4/right-active.png
/usr/share/themes/Moheli/xfwm4/right-active.xpm
/usr/share/themes/Moheli/xfwm4/right-inactive.png
/usr/share/themes/Moheli/xfwm4/right-inactive.xpm
/usr/share/themes/Moheli/xfwm4/shade-active.png
/usr/share/themes/Moheli/xfwm4/shade-active.xpm
/usr/share/themes/Moheli/xfwm4/shade-inactive.png
/usr/share/themes/Moheli/xfwm4/shade-inactive.xpm
/usr/share/themes/Moheli/xfwm4/shade-pressed.png
/usr/share/themes/Moheli/xfwm4/shade-pressed.xpm
/usr/share/themes/Moheli/xfwm4/shade-toggled-active.png
/usr/share/themes/Moheli/xfwm4/shade-toggled-active.xpm
/usr/share/themes/Moheli/xfwm4/shade-toggled-inactive.png
/usr/share/themes/Moheli/xfwm4/shade-toggled-inactive.xpm
/usr/share/themes/Moheli/xfwm4/shade-toggled-pressed.png
/usr/share/themes/Moheli/xfwm4/shade-toggled-pressed.xpm
/usr/share/themes/Moheli/xfwm4/stick-active.png
/usr/share/themes/Moheli/xfwm4/stick-active.xpm
/usr/share/themes/Moheli/xfwm4/stick-inactive.png
/usr/share/themes/Moheli/xfwm4/stick-inactive.xpm
/usr/share/themes/Moheli/xfwm4/stick-pressed.png
/usr/share/themes/Moheli/xfwm4/stick-pressed.xpm
/usr/share/themes/Moheli/xfwm4/stick-toggled-active.png
/usr/share/themes/Moheli/xfwm4/stick-toggled-active.xpm
/usr/share/themes/Moheli/xfwm4/stick-toggled-inactive.png
/usr/share/themes/Moheli/xfwm4/stick-toggled-inactive.xpm
/usr/share/themes/Moheli/xfwm4/stick-toggled-pressed.png
/usr/share/themes/Moheli/xfwm4/stick-toggled-pressed.xpm
/usr/share/themes/Moheli/xfwm4/themerc
/usr/share/themes/Moheli/xfwm4/title-1-active.png
/usr/share/themes/Moheli/xfwm4/title-1-active.xpm
/usr/share/themes/Moheli/xfwm4/title-1-inactive.png
/usr/share/themes/Moheli/xfwm4/title-1-inactive.xpm
/usr/share/themes/Moheli/xfwm4/title-2-active.png
/usr/share/themes/Moheli/xfwm4/title-2-active.xpm
/usr/share/themes/Moheli/xfwm4/title-2-inactive.png
/usr/share/themes/Moheli/xfwm4/title-2-inactive.xpm
/usr/share/themes/Moheli/xfwm4/title-3-active.png
/usr/share/themes/Moheli/xfwm4/title-3-active.xpm
/usr/share/themes/Moheli/xfwm4/title-3-inactive.png
/usr/share/themes/Moheli/xfwm4/title-3-inactive.xpm
/usr/share/themes/Moheli/xfwm4/title-4-active.png
/usr/share/themes/Moheli/xfwm4/title-4-active.xpm
/usr/share/themes/Moheli/xfwm4/title-4-inactive.png
/usr/share/themes/Moheli/xfwm4/title-4-inactive.xpm
/usr/share/themes/Moheli/xfwm4/title-5-active.png
/usr/share/themes/Moheli/xfwm4/title-5-active.xpm
/usr/share/themes/Moheli/xfwm4/title-5-inactive.png
/usr/share/themes/Moheli/xfwm4/title-5-inactive.xpm
/usr/share/themes/Moheli/xfwm4/top-left-active.png
/usr/share/themes/Moheli/xfwm4/top-left-active.xpm
/usr/share/themes/Moheli/xfwm4/top-left-inactive.png
/usr/share/themes/Moheli/xfwm4/top-left-inactive.xpm
/usr/share/themes/Moheli/xfwm4/top-right-active.png
/usr/share/themes/Moheli/xfwm4/top-right-active.xpm
/usr/share/themes/Moheli/xfwm4/top-right-inactive.png
/usr/share/themes/Moheli/xfwm4/top-right-inactive.xpm
/usr/share/xfwm4/defaults

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xfwm4/COPYING

%files locales -f xfwm4.lang
%defattr(-,root,root,-)

